asynctest: $(PHP_ASYNCTEST_BINARIES)

ASYNCTEST_BUILD = $(LIBTOOL) --tag=CC --mode=link $(CC) -export-dynamic $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(EXTRA_LDFLAGS_PROGRAM) $(LDFLAGS) $(PHP_RPATHS) $(PHP_GLOBAL_OBJS) $(PHP_BINARY_OBJS) $(EXTRA_LIBS) $(ZEND_EXTRA_LIBS) $(CMOCKA_LIBS)

sapi/asynctest/tests/test-listen_uaf: $(PHP_GLOBAL_OBJS) $(PHP_SAPI_OBJS) $(PHP_ASYNCTEST_LISTEN_UAF_OBJS)
	$(ASYNCTEST_BUILD) $(PHP_ASYNCTEST_LISTEN_UAF_OBJS) -o $@

sapi/asynctest/tests/test-timer_overflow: $(PHP_GLOBAL_OBJS) $(PHP_SAPI_OBJS) $(PHP_ASYNCTEST_TIMER_OVERFLOW_OBJS)
	$(ASYNCTEST_BUILD) $(PHP_ASYNCTEST_TIMER_OVERFLOW_OBJS) -o $@
